FROM node:16.20.0-alpine3.18 as build-stage
WORKDIR /usr/src/app
COPY ./material-applications/example-frontend/ .
RUN npm install && npm run build

FROM node:16.20.0-alpine3.18
EXPOSE 5000
WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/build /usr/src/app/build
RUN npm install -g serve && adduser -D appuser
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]
