version: '3.8'

services:
    part2_10_frontend_service:
      build:
        context: .
        dockerfile: Dockerfile-frontend
#      ports:
#        - 5000:5000
      container_name: part2_10_frontend_container

    part2_10_backend_service:
      environment: 
       REDIS_HOST: part2_10_redis_container
       POSTGRES_HOST: part2_10_postgres_container
      depends_on:
       - part2_10_redis_service
       - part2_10_postgres_service
      build:
        context: .
        dockerfile: Dockerfile-backend
 #     ports:
 #       - 8000:8000
      command: ["./server"]
      container_name: part2_10_backend_container

    part2_10_redis_service:
      image: redis:7.0.11-alpine3.18
      restart: unless-stopped
      command: ["redis-server"]
      container_name: part2_10_redis_container
        
    part2_10_postgres_service:
      image: postgres:15.3-alpine3.18
      restart: unless-stopped
      environment:
        POSTGRES_HOST: part2_10_postgres_container
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres
      container_name: part2_10_postgres_container
      volumes:
        - type: bind
          source: ./database
          target: /var/lib/postgresql/data

    part2_10_nginx_service:
      image: nginx:1.23.4-alpine3.17
      depends_on:
        - part2_10_frontend_service
        - part2_10_backend_service
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      container_name: part2_10_nginx_container
        
        
    
    