FROM node:16.20.0-buster
EXPOSE 5000
WORKDIR /usr/src/app
COPY ./material-applications/example-frontend/ .
RUN npm install && npm run build &&  npm install -g serve && useradd appuser
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]
