FROM golang:1.20.4-alpine3.18
EXPOSE 8000
ENV PORT=8000
# Needed Part1_12 to pass an url through the cors check. Default: https://example.com
ENV REQUEST_ORIGIN=http://127.0.0.1
# # Needed Part2.4 The hostname for redis. (port will default to 6379, the default for Redis)
ENV REDIS_HOST=part2_9_redis_container
# # Needed Part2.6 The hostname for postgres database. (port will default to 5432 the default for Postgres)
ENV POSTGRES_HOST=part2_9_postgres_container
# # Needed Part2.6 database user. Default: postgres
ENV POSTGRES_USER=postgres
# # Needed Part2.6 database password. Default: postgres
ENV POSTGRES_PASSWORD=postgres
# # Needed Part2.6 database name. Default: postgres
ENV POSTGRES_DATABASE=postgres

WORKDIR /usr/src/app
COPY ./material-applications/example-backend/ .
RUN go build
RUN go test ./...
