# https://chemidy.medium.com/create-the-smallest-and-secured-golang-docker-image-based-on-scratch-4752223b7324
FROM golang:1.20.5-alpine3.18 as build-stage
EXPOSE 8080
# ENV PORT=8080
# Needed Part1_12 to pass an url through the cors check. Default: https://example.com
# ENV REQUEST_ORIGIN=http://127.0.0.1:5000
WORKDIR /usr/src/app
COPY ./material-applications/example-backend/ .
# RUN go build -o /go/bin/backend && go test ./... 
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/backend && go test ./...

FROM scratch
COPY --from=build-stage /go/bin/backend /go/bin/backend